// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"database/sql"
)

type Post struct {
	ID        int64          `json:"id"`
	Content   sql.NullString `json:"content"`
	CreatedAt string         `json:"created_at"`
}
